import {t_adminNormal} from "./adminNormal.d";
import {t_admin_db_audit} from "./admin_db_audit.d";
import {t_ait} from "./ait.d";
import {t_cnooc} from "./cnooc.d";
import {t_ctyun} from "./ctyun.d";
import {t_doc} from "./doc.d";
import {t_hdr_y} from "./hdr_y.d";
import {t_hdr_y_oc} from "./hdr_y_oc.d";
import {t_internet_portal} from "./internet_portal.d";
import {t_internet_portal_oc} from "./internet_portal_oc.d";
import {t_mo_ack} from "./mo_ack.d";
import {t_mo_oc} from "./mo_oc.d";
import {t_mo_vdun_oc} from "./mo_vdun_oc.d";
import {t_rccwl} from "./rccwl.d";
import {t_undefined} from "./undefined.d";
import {t_vdun} from "./vdun.d";
import {t_whistle} from "./whistle.d";
import {t_xxxxxxx} from "./xxxxxxx.d";
import {t_yapi} from "./yapi.d";
import {t_zl} from "./zl.d";
export type t_api = {
	adminNormal:t_adminNormal;
admin_db_audit:t_admin_db_audit;
ait:t_ait;
cnooc:t_cnooc;
ctyun:t_ctyun;
doc:t_doc;
hdr_y:t_hdr_y;
hdr_y_oc:t_hdr_y_oc;
internet_portal:t_internet_portal;
internet_portal_oc:t_internet_portal_oc;
mo_ack:t_mo_ack;
mo_oc:t_mo_oc;
mo_vdun_oc:t_mo_vdun_oc;
rccwl:t_rccwl;
undefined:t_undefined;
vdun:t_vdun;
whistle:t_whistle;
xxxxxxx:t_xxxxxxx;
yapi:t_yapi;
zl:t_zl;
};