import {t_admin_db_audit} from "./admin_db_audit.d";
import {t_ait} from "./ait.d";
import {t_anxin} from "./anxin.d";
import {t_cnooc} from "./cnooc.d";
import {t_ctyun} from "./ctyun.d";
import {t_hdr_y} from "./hdr_y.d";
import {t_internet_portal} from "./internet_portal.d";
import {t_lingyun_perf} from "./lingyun_perf.d";
import {t_mo_ack} from "./mo_ack.d";
import {t_shenjiaosuo} from "./shenjiaosuo.d";
import {t_test} from "./test.d";
import {t_undefined} from "./undefined.d";
import {t_vdun} from "./vdun.d";
import {t_whistle} from "./whistle.d";
import {t_xxxxxxx} from "./xxxxxxx.d";
import {t_yapi} from "./yapi.d";
import {t_yingfang_oc} from "./yingfang_oc.d";
import {t_zl} from "./zl.d";
import {t__hbr_y_oc} from "./_hbr_y_oc.d";
import {t__hdr_y_oc} from "./_hdr_y_oc.d";
import {t__internet_portal_oc} from "./_internet_portal_oc.d";
import {t__mo_oc} from "./_mo_oc.d";
import {t__mo_vdun_oc} from "./_mo_vdun_oc.d";
import {t__yingfang_oc} from "./_yingfang_oc.d";
export type t_opts = {
	admin_db_audit:t_admin_db_audit;
ait:t_ait;
anxin:t_anxin;
cnooc:t_cnooc;
ctyun:t_ctyun;
hdr_y:t_hdr_y;
internet_portal:t_internet_portal;
lingyun_perf:t_lingyun_perf;
mo_ack:t_mo_ack;
shenjiaosuo:t_shenjiaosuo;
test:t_test;
undefined:t_undefined;
vdun:t_vdun;
whistle:t_whistle;
xxxxxxx:t_xxxxxxx;
yapi:t_yapi;
yingfang_oc:t_yingfang_oc;
zl:t_zl;
_hbr_y_oc:t__hbr_y_oc;
_hdr_y_oc:t__hdr_y_oc;
_internet_portal_oc:t__internet_portal_oc;
_mo_oc:t__mo_oc;
_mo_vdun_oc:t__mo_vdun_oc;
_yingfang_oc:t__yingfang_oc;
};